### PR TITLE
Update umapi.py - fixes #793

### LINKED ISSUE #793: Add possibility to createFederatedID in a single action with email diff from username
Is your feature request related to a problem? Please describe.
currently the accounts that should have username different than email and both being an email formatted value, need a 2 step process: create with email == username, then update the username

Describe the solution you'd like
The UMAPI allows this type of JSON format:

[{"user": "username@domain.com",
 "do": [
    {"createFederatedID": {"email": "some_email@domain.com", 
                           "option": "ignoreIfAlreadyExists", 
                           "firstname": "different", 
                           "lastname": "values", 
                           "country": "GB" }
    }
 ]
}]
This creates an account in Admin Console in a single call, no need to chain an 'update' action inside the 'do' statement anymore
The benefit is that you can create accounts in trustee orgs directly without the current problem of creating with username==email.

Describe alternatives you've considered
.

Additional context
user-sync.py project will also have a PR added to support this create action

### PR DESCRIPTION
**Pull request by Luci2015**
fixes #793

## Summary
* makes possible creation of T3 accounts in a single createFderatedID call, without a chained update call

## Testing Steps
* make sure you create a build by incorporating also the change from the enhancement 102 on the umapi-client.py 
* use a source of directory for which username != email and both are email formatted values
* run the tool in this setup and observe the createFederatedID no longer mention 'update' action and also the accounts get created with email != username in admin console  

Fixes #793

### CODE REVIEW

**Comment by adorton-adobe** [comment]
I've published an update to umapi-client that includes the fix (v2.20). Will you please update your branch with that version so I can do some testing?

**Comment by adorton-adobe** [comment]
This is going to take some time to test. Will you please also ensure that all tests pass? The build is breaking because at least one test is currently failing.

**Comment by Luci2015** [comment]
Tests will continue to fail because your env still builds with `umapi-client==2.19` and also some tests are set up to use the separate `update` statement inside the create call, when in fact that is no longer needed (check my latest test changes).

**Comment by adorton-adobe** [comment]
Your branch still has `umapi-client==2.19` in the setup file. I updated my copy of your branch locally in order to test the updated client.

https://github.com/Luci2015/user-sync.py/blob/patch-1/setup.py#L54

And the test isn't failing because my environment is wrong. Once you update your branch's setup.py the test will still fail. The failing test is `tests/test_umapi_engine.py::test_create_umapi_commands_for_directory_user` which contains a check that ensures the UST is constructing the two-step create/update structure correctly. 

```
>       assert vars(result) == vars(commands)
E       AssertionError: assert {'do_list': [...ratedID', ...} == {'do_list': [...ratedID', ...}
E         Omitting 3 identical items, use -vv to show
E         Differing items:
E         {'username': 'different@example.com'} != {'username': 'user1@example.com'}
E         {'do_list': [('create', {'country': 'US', 'email': 'user1@example.com', 'first_name': 'user1 First', 'last_name': 'user1 Last', ...})]} != {'do_list': [('create', {'country': 'US', 'email': 'user1@example.com', 'first_name': 'user1 First', 'last_name': 'user1 Last', ...}), ('update', {'email': 'user1@example.com', 'username': 'different@example.com'})]}
E         Full diff:
E           {
E            'do_list': [('create',
E                         {'country': 'US',
E                          'email': 'user1@example.com',
E                          'first_name': 'user1 First',
E                          'last_name': 'user1 Last',
E         -                'on_conflict': <IfAlreadyExistsOptions.ignoreIfAlreadyExists: 1>}),
E         +                'on_conflict': <IfAlreadyExistsOptions.ignoreIfAlreadyExists: 1>})],
E         ?                                                                                  +
E         -              ('update',
E         -               {'email': 'user1@example.com',
E         -                'username': 'different@example.com'})],
E            'domain': 'example.com',
E            'email': 'user1@example.com',
E            'identity_type': 'federatedID',
E         -  'username': 'user1@example.com',
E         ?               ^^  ^
E         +  'username': 'different@example.com',
E         ?               ^^^^  ^^^
E           }
```

You can probably just remove the part of the test that performs this check. If you've already fixed the test (and setup file) then you probably just need to push your changes.

**Comment by Luci2015** [comment]
opened from patch-1

**Comment by Luci2015** [comment]
done! I did not notice it was all building from patch-1 instead of v2.
Now the tests, setup and umami.py all come from patch-1 and tests pass.

**Review by adorton-adobe — APPROVED** [review]
Still some testing left but I think we can merge

**Pull request merged**
