### PR TITLE
Store credman mb

### PR DESCRIPTION
**Pull request by mbonish**
store_ key() and save() for sub classes -ldap, umapi, okta, and console

### CODE REVIEW

**Comment by adorton-adobe** [comment]
This appears to be related to credential storage. Is that feature ready for review and merging into the main repo?

**Comment by vossen-adobe** [comment]
@adorton-adobe  No - this was against the wrong repo/branch I think. @mbonish can you redo this on dme/cred?

**Comment by adorton-adobe** [comment]
Ahh, no worries. Please delete this after making the PR on the dmeservices repo.

**Comment by vossen-adobe** [comment]
I don't think I have the ability to delete PR's, just close?

**Pull request closed without merging**
