### PR TITLE
Update model.py

### LINKED ISSUE #830: Sign sync is failing
**Description**
Sign sync started to fail with this message: 
`TypeError: sign_client.model.BooleanSettingsInfo() argument after ** must be a mapping, not bool`

```
2023-11-20 09:23:19 43895 ERROR asyncio - Task exception was never retrieved
future: <Task finished name='Task-86' coro=<SignClient._get_user_groups() done, defined at /Users/user/user-sync.py-2.10.0rc1/ENV/lib/python3.10/site-packages/sign_client/client.py:277> exception=TypeError('sign_client.model.BooleanSettingsInfo() argument after ** must be a mapping, not bool')>
Traceback (most recent call last):
  File "/Users/user/user-sync.py-2.10.0rc1/ENV/lib/python3.10/site-packages/sign_client/client.py", line 284, in _get_user_groups
    groups = UserGroupsInfo.from_dict(groups)
  File "/Users/user/user-sync.py-2.10.0rc1/ENV/lib/python3.10/site-packages/sign_client/model.py", line 211, in from_dict
    return cls([UserGroupInfo.from_dict(v) for v in dct['groupInfoList']])
  File "/Users/user/user-sync.py-2.10.0rc1/ENV/lib/python3.10/site-packages/sign_client/model.py", line 211, in <listcomp>
    return cls([UserGroupInfo.from_dict(v) for v in dct['groupInfoList']])
  File "/Users/user/user-sync.py-2.10.0rc1/ENV/lib/python3.10/site-packages/sign_client/model.py", line 199, in from_dict
    new_dct[k] = SettingsInfo.from_dict(v)
  File "/Users/user/user-sync.py-2.10.0rc1/ENV/lib/python3.10/site-packages/sign_client/model.py", line 180, in from_dict
    new_dct = {k: BooleanSettingsInfo.from_dict(v) for k, v in dct.items()}
  File "/Users/user/user-sync.py-2.10.0rc1/ENV/lib/python3.10/site-packages/sign_client/model.py", line 180, in <dictcomp>
    new_dct = {k: BooleanSettingsInfo.from_dict(v) for k, v in dct.items()}
  File "/Users/user/user-sync.py-2.10.0rc1/ENV/lib/python3.10/site-packages/sign_client/model.py", line 165, in from_dict
    return cls(**dct)
TypeError: sign_client.model.BooleanSettingsInfo() argument after ** must be a mapping, not bool
```

**Steps to reproduce**
* run UST with sign-sync option as usual

**Expected behavior**
no failure during sync

**Environment**
 - UST version: latest
 - OS type and version: all

### PR DESCRIPTION
**Pull request by Luci2015**
Instead of going through the details of SettingsInfo statement of each group, just copy the entire statement from the Sign response

Fixes #830

### CODE REVIEW

**Comment by bhunut-adobe** [comment]
@Luci2015, We need to utilize the Class model that @adorton-adobe defined for settings.

**Comment by Luci2015** [comment]
@bhunut-adobe : 
reviewed fix for keeping class model as before and check if a boolean is sent over instead of a dict
_canUseMulticastWorkflows_ will not even appear in the final SettingsInfo class because of the _remove_unknown_keys_ function which limits results to:
    libaryDocumentCreationVisible: BooleanSettingsInfo = None
    sendRestrictedToWorkflows: BooleanSettingsInfo = None
    userCanSend: BooleanSettingsInfo = None
    userManagedWorkflowsEnabled: BooleanSettingsInfo = None
    allowedToShareUserCreatedWorkflows: BooleanSettingsInfo = None

**Comment by bhunut-adobe** [comment]
@Luci2015 Why not just add canUseMulticastWorkflows attribute to SettingsInfo class?

**Comment by ddybvig-adobe** [comment]
I tried adding the canUseMultiCastWorkflows field to SettingsInfo, but I still get the same error as before.

**Comment by Luci2015** [comment]
@bhunut-adobe : Andrew discarded also some other statements that come from the Sign response (last time it was `widgetCreationVisible`). It's the reason why he added the  _remove_unknown_keys_ function in the first place. Only the 5 above were kept for some reason.
I can add it, no issue, but the proposed solution should be sufficient to get back to the previous state of the tool -> your call

**Review by ddybvig-adobe — APPROVED** [review]
Approved.

**Comment by ddybvig-adobe** [comment]
Hi @Luci2015 , it looks like Sign Engineering fixed this on stage as shown [here](https://secure.na1.adobesignstage.com/public/docs/restapi/v6#!/users/getGroupsOfUser). For now, I am going to leave this PR unmerged in hopes that they deploy this change to production soon. If a need does arise for a signed build and release of UST before then, let me know.

**Pull request closed without merging**
