### PR TITLE
Update UST/doc for api_key and tech_acct

### LINKED ISSUE #635: Update UST/doc for api_key and tech_acct
Application and documentation changes related to terminology updates in the Adobe IO console

### PR DESCRIPTION
**Pull request by mbonish**
Updated documentation and config files to reflect changes to UMAPI.
UST documentation, example configs, etc use client_id instead of api_key and tech_acct instead of tech_acct_id.

Fixes #635

### CODE REVIEW

**Comment by adorton-adobe** [comment]
Does this PR need to be submitted to a dmeservices branch?

**Comment by mbonish** [comment]
Usually yes, for this one Danimae asked for it to be off apiplatform.

On May 27, 2020, at 12:19 PM, Andrew Dorton <notifications@github.com>
wrote:

﻿

Does this PR need to be submitted to a dmeservices branch?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/adobe-apiplatform/user-sync.py/pull/607#issuecomment-634815007>,
or unsubscribe

**Comment by adorton-adobe** [comment]
Thank you for clarifying. Will you please update the title and description to describe the updates we're proposing in this PR?

**Comment by mbonish** [comment]
oh yep, I will fix that.

**Comment by adorton-adobe** [comment]
Thanks, can you please also update the PR title? A link to this PR will go into the release notes of v2.6.1 and I want to make sure it makes sense to those reading the release notes.

**Review by adorton-adobe — APPROVED** [review]

**Pull request merged**
