### PR TITLE
Convert docs folder for readiness with GitHub pages

### PR DESCRIPTION
**Pull request by adobeDan**
* Convert the User Sync Guide to markdown format
* Remove the Word and PDF versions
* Add an index.md file to be the root of the docs

### CODE REVIEW

**Comment by adobeDan** [comment]
Hi @phil-levy and @jabogart, can you please navigate to the [docs root in this pulled branch](https://github.com/adobe-apiplatform/user-sync.py/blob/convert-user-guide-to-md/docs/index.md), and review the (brief) root page and the converted User Sync Guide?  Thanks!

**Comment by phil-levy** [comment]
Actually, we at least shouldn't remove the pdf as we have given out links to that file which will be broken if it disappears.

**Comment by jameslockman** [comment]
Please do not move the PDF. We have distributed the link to the PDF pretty widely up to now.

James

James Lockman  | Manager, Digital Media Services  |  Adobe
p. 917.934.0849<tel:19179340849>  |  c. 917.284.2268<tel:19172842268>  |  @jameslockman<http://twitter.com/jameslockman>  |  blog<http://blogs.adobe.com/jlockman>  |  jlockman@adobe.com<mailto:jlockman@adobe.com>

**Comment by adobeDan** [comment]
OK, I will restore the PDF from Master once I merge to v1.

**Pull request merged**
