### PR TITLE
Integrate the extension example files from v1 for use on master.

### PR DESCRIPTION
**Pull request by adobeDan**
Remove references to Adobe ID as an default new user type.

This is meant to be part of the doc of v1.1, the existing release sitting on master.

### CODE REVIEW

**Comment by adobeDan** [comment]
Hey @Metasemi, I thought you might enjoy seeing your examples and code make it into the 1.1 release.  Also, have fun looking at the v1 branch, which "does the right thing" for removing groups that were added by extensions (if the extension changes its mind or the user is deleted).

**Comment by adobeDan** [comment]
@phil-levy Reminder: You or @Metasemi need to approve before I can merge.

**Comment by Metasemi** [comment]
Hey guys! My personal mail got way backlogged at The End Of Time and I'm just seeing this now. I did see the commits go by for removing extension-mandated-but-not-anymore group assignments - got a big kick out of that. I'll take a look at the PR... If I'm under the illusion I have anything intelligent to say, I'll spit it out!

**Comment by Metasemi** [comment]
@adobeDan @phil-levy Guess I should throw a couple at-signs at you since PR has been closed :)

**Comment by Metasemi** [comment]
@adobeDan @phil-levy It all looks good, great to see! My eyes feel so relaxed due to relief from being relentlessly hammered by redundant parentheses. As to the lists,

:)

**Comment by adobeDan** [comment]
@Metasemi Ha!  Good one,

**Pull request merged**
