### PR TITLE
Replace  / Remove unused methods

### PR DESCRIPTION
**Pull request by vossen-adobe**
make_stray_key_map simply returns an empty dictionary and is only used once in the code.  It makes sense to remove it.  The return value no longer matches the comments, so I'm assuming it had a greater purpose in the past.

Also, several methods are no longer used anywhere in the code:

calculate_groups_to_add
calculate_groups_to_remove
get_new _groups

Removed these.

### CODE REVIEW

**Comment by vossen-adobe** [comment]
Also,  the ubuntu builds are failing because of a jeepney dependency issue (across the board I think)

**Comment by adorton-adobe** [comment]
@vossen-adobe - just a reminder that we can't merge this until all CI checks pass

**Comment by vossen-adobe** [comment]
Will do today - it's raining issues over here!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by vossen-adobe** [comment]
@adorton-adobe Good to go!

**Pull request merged**
